In [5]:
import pandas as pd
import numpy as np
from collections import Counter
import math
import json

In [6]:
df = pd.read_csv("user-song_rating.tsv", sep='\t', header=None,
names=[
        'user_id', 'timestamp', 'artist_id', 'artist_name', 'track_id', 'track_name'
    ],
skiprows=[
        2120260-1, 2446318-1, 11141081-1,
        11152099-1, 11152402-1, 11882087-1,
        12902539-1, 12935044-1, 17589539-1
    ]
,parse_dates=["timestamp"])

In [7]:
df.head()

,user_id,timestamp,artist_id,artist_name,track_id,track_name
0,user_000001,2009-05-04 23:08:57+00:00,f1b1cf71-bd35-4e99-8624-24a6e15f133a,Deep Dish,NaN,Fuck Me Im Famous (Pacha Ibiza)-09-28-2007
1,user_000001,2009-05-04 13:54:10+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Composition 0919 (Live_2009_4_15)
2,user_000001,2009-05-04 13:52:04+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Mc2 (Live_2009_4_15)
3,user_000001,2009-05-04 13:42:52+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Hibari (Live_2009_4_15)
4,user_000001,2009-05-04 13:42:11+00:00,a7f7df4a-77d8-4f12-8acd-5c60c93f4de8,坂本龍一,NaN,Mc1 (Live_2009_4_15)

In [8]:
df["year"]=df["timestamp"].dt.year
df["month"]=df["timestamp"].dt.month

In [9]:
# major portion of the data is from 3 years (2006-2008) and hence we will use these 3 years
df.groupby(["year"])[["user_id"]].count()

      user_id
year
2005  1070320
2006  4251472
2007  5323832
2008  5917696
2009  2535531
2010        1
2013        1

In [10]:
df=df.loc[df.year.isin([2006,2007,2008])].reset_index(drop=True)

In [11]:
df.head()

,user_id,timestamp,artist_id,artist_name,track_id,track_name,year,month
0,user_000001,2008-12-31 16:53:59+00:00,4967c0a1-b9f3-465e-8440-4598fd9fc33c,Enya,bd915801-db41-4b75-9b0a-94c34d1fa387,Trains And Winter Rains,2008,12
1,user_000001,2008-12-31 16:50:19+00:00,4967c0a1-b9f3-465e-8440-4598fd9fc33c,Enya,NaN,O Come O Come Emmanuel [Album]/Album,2008,12
2,user_000001,2008-12-31 16:47:19+00:00,4967c0a1-b9f3-465e-8440-4598fd9fc33c,Enya,307307e5-aa4a-4de4-a96e-5a260fb3bb80,White Is In The Winter Night,2008,12
3,user_000001,2008-12-31 16:42:32+00:00,4967c0a1-b9f3-465e-8440-4598fd9fc33c,Enya,14f3f3b8-5750-4343-ab9b-30de8ed78ebb,Journey Of The Angels,2008,12
4,user_000001,2008-12-31 16:39:16+00:00,4967c0a1-b9f3-465e-8440-4598fd9fc33c,Enya,NaN,And Winter Came [Album]/Album,2008,12

In [12]:
df.user_id.nunique()

942

In [13]:
df.loc[df["track_id"].isna()]["track_name"].value_counts()

Intro                           2097
Untitled                        1834
Bonus Track                     1680
There There                      952
La Paloma                        881
                                ...
Montana Ft. Deceptikon             1
02 - Into The Light                1
The Pod. El Manor De La Nova       1
A1 - Me Vs. Caplocks               1
Truly & Really                     1
Name: track_name, Length: 382498, dtype: int64

In [14]:
df=df.loc[~df["track_name"].isna()]

In [15]:
df=df.loc[~df["track_name"].isna()].reset_index(drop=True)

In [16]:
df.groupby(["year"])[["user_id"]].count()

      user_id
year
2006  4251461
2007  5323832
2008  5917696

In [17]:
user2idx={}
song2idx={}
#count=0
user_set=set(df.user_id.values)
song_set=set(df.track_name.values)

In [18]:
count=0
for i in user_set:
    user2idx[i]=count
    count+=1

In [19]:
count=0
for i in song_set:
    song2idx[i]=count
    count+=1

In [20]:
df["user_idx"]=df.apply(lambda x: user2idx[x.user_id],axis=1)
df["song_idx"]=df.apply(lambda x: song2idx[x.track_name],axis=1)

In [21]:
pd.Series(song2idx.keys())[pd.Series(song2idx.keys()).str.contains('ghetto|Ghetto')]

5117             Symphony In C Major: Larghetto
7802             Ghetto Fabulous (Dopamine Mix)
9145                     Don'T Call It A Ghetto
9817                 Ghetto Box (Album Version)
10653                               Dave Ghetto
                          ...
939938    Ghetto Children Ft. Element Scripture
940013                              Ghetto Blue
940226                       Born In Tha Ghetto
941343                          Dub Inna Ghetto
949467                 Ghetto Musick (Club Mix)
Length: 605, dtype: object

In [22]:
max_year=df['year'].max()
max_month=12

In [23]:
df.loc[:,"freq"]=1

In [24]:
df_subset=df.groupby(["user_idx","song_idx","year","month"],as_index=False).agg({"freq":"sum"}).assign(rel_weight=lambda x: 1-((12*(max_year-x.year) + (max_month-x.month))/36))

In [25]:
df_subset.loc[:,"weighted_freq"]=df_subset["freq"]*df_subset["rel_weight"]

In [26]:
df_interaction=df_subset.groupby(["user_idx","song_idx"],as_index=False).agg({"freq":'sum',"weighted_freq":"sum"})

In [27]:
df_subset

         user_idx  song_idx  year  month  freq  rel_weight  weighted_freq
0               0        83  2007     12     1    0.666667       0.666667
1               0        83  2008      4     2    0.777778       1.555556
2               0       117  2007     12     4    0.666667       2.666667
3               0       117  2008     12     1    1.000000       1.000000
4               0       165  2007      9     1    0.583333       0.583333
...           ...       ...   ...    ...   ...         ...            ...
8520524       941    946129  2008     10     3    0.944444       2.833333
8520525       941    947470  2007      9     1    0.583333       0.583333
8520526       941    949006  2007      3     1    0.416667       0.416667
8520527       941    949188  2007      3     1    0.416667       0.416667
8520528       941    949188  2007      6     1    0.500000       0.500000

[8520529 rows x 7 columns]

## Computing Inverse Song Frequency

In [28]:
df_1=df_subset.groupby(["year","month"],as_index=False)["user_idx"].nunique().rename(columns={"user_idx":"n_users"})
df_2=df_subset.groupby(["year","month","song_idx"],as_index=False)["user_idx"].nunique().rename(columns={"user_idx":"df"})
df_merge=df_2.merge(df_1,how="inner",on=["year","month"])

In [29]:
df_merge["inverse_song_freq"]=df_merge.apply(lambda x:math.log((x.n_users/(1+x.df)),2),axis=1)

## Computing TF-IDF

In [30]:
df_final=df_subset.merge(df_merge,how="inner",on=["year","month","song_idx"])

In [31]:
df_final.loc[:,"tf-idf"]=df_final["weighted_freq"]*df_final["inverse_song_freq"]

In [32]:
df_final=df_final.groupby(["user_idx","song_idx"],as_index=False)["tf-idf"].sum()

In [56]:
df_final.shape

(3696755, 3)

In [35]:
# a dictionary to look up ratings
usersong2tfidf = {}
print("Calling: update_user2song_and_song2user")
count = 0

Calling: update_user2song_and_song2user

In [58]:
df_final[df_final["user_idx"]==0]

      user_idx  song_idx     tf-idf
0            0        83  17.286297
1            0       117  30.094128
2            0       165  17.772142
3            0       474   2.023054
4            0       720   9.506027
...        ...       ...        ...
5348         0    949669   6.798296
5349         0    949700  22.020305
5350         0    950086   8.375039
5351         0    950548  12.604108
5352         0    950570   8.620194

[5353 rows x 3 columns]

In [37]:
def update_user2song_and_song2user(row):
    
    global count
    count += 1
#     if count % 100000 == 0:
#         print("processed: %.3f" % (float(count)/cutoff))

    i = int(row.user_idx)
    j = int(row.song_idx)

    usersong2tfidf[(i,j)] = row["tf-idf"]

In [40]:
df_final.apply(update_user2song_and_song2user,axis=1)

0          None
1          None
2          None
3          None
4          None
           ...
3696750    None
3696751    None
3696752    None
3696753    None
3696754    None
Length: 3696755, dtype: object

In [47]:
usersong2tfidf_new = {str(key): val for key, val in usersong2tfidf.items()}

In [50]:
with open('user_song_tfidf.txt', 'w') as convert_file:
     convert_file.write(json.dumps(usersong2tfidf_new))

In [51]:
data = json.load(open('user_song_tfidf.txt'))

In [54]:
import ast
a = '(0,2)'
ast.literal_eval(a)

(0, 2)

In [55]:
new_data = {ast.literal_eval(key): val for key, val in data.items()}
new_data

{(0, 83): 17.28629721437562,
 (0, 117): 30.094128078898613,
 (0, 165): 17.77214150723554,
 (0, 474): 2.023054008169132,
 (0, 720): 9.506027043518767,
 (0, 746): 7.556242818183537,
 (0, 773): 7.818535599430455,
 (0, 779): 14.536337920106739,
 (0, 800): 7.832641118955218,
 (0, 1435): 44.25023658808155,
 (0, 1461): 60.248783415427454,
 (0, 1538): 5.887761274999198,
 (0, 1559): 11.119505807354601,
 (0, 1576): 6.383233360138082,
 (0, 1702): 5.465288357811696,
 (0, 2134): 16.554792783085247,
 (0, 2374): 9.479551152853983,
 (0, 2414): 19.05597161959744,
 (0, 2418): 4.9330354286916585,
 (0, 2460): 4.963336753432104,
 (0, 2691): 11.405106600444757,
 (0, 2731): 10.859544323775845,
 (0, 2955): 5.657781197876548,
 (0, 2970): 5.429772161887922,
 (0, 3131): 7.114581672402099,
 (0, 3161): 4.743583227021795,
 (0, 3264): 7.818535599430455,
 (0, 3396): 11.210911164720606,
 (0, 3518): 14.149681249843969,
 (0, 3888): 12.731808751248991,
 (0, 3965): 8.620193878359146,
 (0, 3983): 8.829237820589636,
 (0, 4083): 5.749752852336659,
 (0, 4111): 7.375039431346925,
 (0, 4289): 34.22464736009991,
 (0, 4393): 5.928262526243849,
 (0, 4454): 4.365457509049696,
 (0, 4482): 2.391445371116669,
 (0, 4954): 6.383233360138082,
 (0, 4988): 21.343745017206295,
 (0, 5013): 9.008739008993082,
 (0, 5122): 5.465288357811696,
 (0, 5365): 2.6255056488550004,
 (0, 5594): 2.212706829229649,
 (0, 5645): 19.181517838852898,
 (0, 5764): 15.274967555764619,
 (0, 5797): 5.210022680783289,
 (0, 5989): 5.465288357811696,
 (0, 6121): 7.556242818183537,
 (0, 6163): 5.429772161887922,
 (0, 6343): 8.375039431346924,
 (0, 6453): 8.088570117587354,
 (0, 6882): 2.9425632362924308,
 (0, 6947): 5.657781197876548,
 (0, 7008): 3.983155494259713,
 (0, 7643): 5.563884090906862,
 (0, 7677): 6.383233360138082,
 (0, 7774): 16.069567004559133,
 (0, 7786): 13.177637773096114,
 (0, 7997): 6.103360525855813,
 (0, 8035): 6.383233360138082,
 (0, 8670): 7.020027192522479,
 (0, 9118): 117.57040170627965,
 (0, 9269): 2.8733979594530483,
 (0, 9851): 1.902197315040896,
 (0, 10139): 6.383233360138082,
 (0, 10779): 42.45259635198585,
 (0, 10810): 15.508615196312661,
 (0, 10998): 11.248437390799971,
 (0, 11059): 7.116347895365133,
 (0, 11158): 24.73672143025764,
 (0, 11314): 13.585062112130213,
 (0, 11503): 5.657781197876548,
 (0, 11604): 5.403428358186903,
 (0, 11683): 11.85435724882909,
 (0, 11738): 15.63707119886091,
 (0, 11782): 14.397527467482748,
 (0, 11921): 8.088570117587354,
 (0, 12716): 5.657781197876548,
 (0, 12780): 7.519856575219566,
 (0, 12813): 21.531594608049925,
 (0, 12927): 17.24277768391393,
 (0, 13004): 5.976254701804648,
 (0, 13105): 6.383233360138082,
 (0, 13312): 6.383233360138082,
 (0, 13535): 17.217349230909043,
 (0, 13551): 25.4003176497954,
 (0, 13573): 2.6255056488550004,
 (0, 13575): 5.429772161887922,
 (0, 13871): 17.451030039652235,
 (0, 13950): 70.73478643708064,
 (0, 14294): 10.559237073059272,
 (0, 14557): 5.657781197876548,
 (0, 14764): 8.303748712661687,
 (0, 14837): 15.870399814181672,
 (0, 15231): 62.875266888423404,
 (0, 15258): 7.556242818183537,
 (0, 15334): 32.555652849514345,
 (0, 15346): 7.7548058465309175,
 (0, 15430): 7.556242818183537,
 (0, 15581): 2.0971848152812815,
 (0, 15758): 7.821217533004591,
 (0, 15779): 3.8743527795406045,
 (0, 15854): 23.524645654080057,
 (0, 15886): 4.963336753432104,
 (0, 15968): 5.657781197876548,
 (0, 16263): 17.950728374955098,
 (0, 16363): 3.706463828073818,
 (0, 16395): 10.401364424898343,
 (0, 16471): 6.383233360138082,
 (0, 16503): 11.315562395753096,
 (0, 16585): 13.497815032540181,
 (0, 16600): 2.6255056488550004,
 (0, 16663): 4.150888835763831,
 (0, 16856): 8.088570117587354,
 (0, 17012): 4.743583227021795,
 (0, 17548): 7.738182863104804,
 (0, 17638): 5.039797161407152,
 (0, 17656): 9.073951693758978,
 (0, 17812): 5.887761274999198,
 (0, 17855): 7.604353102986363,
 (0, 17993): 7.790076930625769,
 (0, 18003): 17.443544605767748,
 (0, 18024): 1.5688639817075625,
 (0, 18040): 4.978847454131363,
 (0, 18346): 3.1273255105329887,
 (0, 18936): 2.6255056488550004,
 (0, 19032): 21.923555085865814,
 (0, 19151): 5.933138455973,
 (0, 19393): 7.915785423922713,
 (0, 19615): 10.716845596854107,
 (0, 19645): 5.7147064826460365,
 (0, 20542): 53.75626630007239,
 (0, 20765): 18.731928765784787,
 (0, 20808): 29.12938299450995,
 (0, 20945): 5.722909484850206,
 (0, 21422): 18.392887602575907,
 (0, 21461): 14.717340729375703,
 (0, 21645): 7.790076930625769,
 (0, 21704): 3.2644871529255317,
 (0, 21732): 5.887761274999198,
 (0, 22201): 7.519856575219566,
 (0, 22596): 7.114581672402099,
 (0, 22980): 4.743583227021795,
 (0, 23019): 2.6255056488550004,
 (0, 23076): 5.429772161887922,
 (0, 23562): 5.210022680783289,
 (0, 23601): 8.569050832906116,
 (0, 23797): 18.687252315429056,
 (0, 23916): 13.161698400543841,
 (0, 24606): 7.341994012169583,
 (0, 24909): 7.556242818183537,
 (0, 25020): 4.160249893688462,
 (0, 25087): 4.557112794597967,
 (0, 25161): 5.657781197876548,
 (0, 25335): 5.887761274999198,
 (0, 25352): 5.928262526243849,
 (0, 25415): 117.28901348779135,
 (0, 25454): 80.02684316848617,
 (0, 25591): 9.672593277311766,
 (0, 26481): 21.343745017206295,
 (0, 26587): 62.64983904035085,
 (0, 26724): 3.972458505004168,
 (0, 26856): 9.90069718620569,
 (0, 26960): 36.875897070565536,
 (0, 27078): 15.841367182804282,
 (0, 27122): 3.983155494259713,
 (0, 27165): 5.429772161887922,
 (0, 27166): 6.383233360138082,
 (0, 27171): 5.8995008062974,
 (0, 27259): 6.383233360138082,
 (0, 27507): 4.836296638655883,
 (0, 27660): 5.887761274999198,
 (0, 27745): 9.164898773692968,
 (0, 27785): 18.20565951010654,
 (0, 28337): 13.172845717281959,
 (0, 28402): 5.210022680783289,
 (0, 28489): 12.299826045205332,
 (0, 28492): 5.0176595006772375,
 (0, 28797): 11.216807314723091,
 (0, 28827): 4.621370370357322,
 (0, 28837): 5.928262526243849,
 (0, 28941): 19.340016768264555,
 (0, 29046): 5.403428358186903,
 (0, 29056): 5.251557239042412,
 (0, 29318): 5.887761274999198,
 (0, 29419): 7.341994012169583,
 (0, 29761): 19.377330683723933,
 (0, 30064): 5.429772161887922,
 (0, 30107): 4.372706970688293,
 (0, 30403): 9.760713233274185,
 (0, 30807): 6.383233360138082,
 (0, 30914): 6.815925614095489,
 (0, 31111): 119.54038812679461,
 (0, 31443): 5.657781197876548,
 (0, 31829): 4.5711337918943995,
 (0, 31892): 13.207065304803363,
 (0, 32184): 11.586043724120398,
 (0, 32357): 31.830646229638287,
 (0, 32729): 5.928262526243849,
 (0, 32814): 17.506302915826325,
 (0, 32913): 5.915607812709628,
 (0, 32994): 5.251011297710001,
 (0, 33697): 12.552016692952872,
 (0, 33792): 7.556242818183537,
 (0, 33962): 17.308740571295775,
 (0, 34343): 4.743583227021795,
 (0, 34627): 5.210022680783289,
 (0, 34687): 13.211336070002806,
 (0, 34955): 9.988208047666015,
 (0, 34983): 17.9408209158136,
 (0, 35011): 17.976489401059453,
 (0, 35048): 16.26750058823986,
 (0, 35220): 6.628770611788349,
 (0, 35401): 2.391445371116669,
 (0, 35666): 5.7147064826460365,
 (0, 35755): 12.009364673993826,
 (0, 35828): 5.657781197876548,
 (0, 36000): 3.308914782816706,
 (0, 36018): 48.569216598913066,
 (0, 36363): 66.07200789344267,
 (0, 36564): 7.818535599430455,
 (0, 36582): 2.6255056488550004,
 (0, 36845): 14.201768959568536,
 (0, 37138): 12.56211882645225,
 (0, 37180): 35.023345078923676,
 (0, 37853): 5.039797161407152,
 (0, 39054): 9.712094475710607,
 (0, 39270): 17.914547806175072,
 (0, 39662): 14.312404951727263,
 (0, 39701): 4.557112794597967,
 (0, 39708): 5.429772161887922,
 (0, 39783): 5.210022680783289,
 (0, 40317): 3.316488827593047,
 (0, 40609): 4.978847454131363,
 (0, 40864): 35.88978342532337,
 (0, 40932): 8.940684202395921,
 (0, 41096): 5.429772161887922,
 (0, 41403): 7.3952246312606515,
 (0, 41500): 5.210022680783289,
 (0, 41570): 2.391445371116669,
 (0, 41906): 5.887761274999198,
 (0, 41985): 13.356644990763023,
 (0, 41995): 8.375039431346924,
 (0, 42047): 18.324332011089414,
 (0, 42296): 10.867803878659837,
 (0, 42372): 26.831788518635584,
 (0, 42465): 9.7069199804539,
 (0, 42525): 10.820355421926273,
 (0, 43012): 17.979854989856435,
 (0, 43706): 4.743583227021795,
 (0, 43720): 2.994002862582504,
 (0, 43829): 2.292172315521667,
 (0, 43863): 12.321460612073519,
 (0, 43936): 4.743583227021795,
 (0, 44108): 10.930576715623392,
 (0, 44310): 2.400527366059493,
 (0, 44537): 9.973128176004543,
 (0, 44555): 2.184862950559213,
 (0, 44650): 1.7253590761413027,
 (0, 44667): 24.894237270656816,
 (0, 44670): 15.395066623869402,
 (0, 45011): 16.876810529443834,
 (0, 45296): 3.756625231909141,
 (0, 45441): 6.450684080337243,
 (0, 46053): 29.82955700857817,
 (0, 46144): 7.818535599430455,
 (0, 46175): 18.47426982448785,
 (0, 46879): 3.819021768267788,
 (0, 47681): 15.39952730828119,
 (0, 48219): 15.580153861251539,
 (0, 48486): 10.63662865200791,
 (0, 48619): 13.20526070499997,
 (0, 48634): 7.818535599430455,
 (0, 48794): 30.747938350358993,
 (0, 48930): 3.2560873601618967,
 (0, 49119): 17.354510710272592,
 (0, 49160): 6.153428358186903,
 (0, 49192): 2.8733979594530483,
 (0, 49199): 24.416005205902813,
 (0, 49534): 17.307485960871478,
 (0, 49731): 5.657781197876548,
 (0, 49796): 10.4970486879027,
 (0, 49886): 5.039797161407152,
 (0, 49914): 6.383233360138082,
 (0, 49948): 2.391445371116669,
 (0, 49949): 2.8733979594530483,
 (0, 50176): 5.657781197876548,
 (0, 50274): 17.32181341029939,
 (0, 50327): 28.29042915355877,
 (0, 50381): 4.43798504603954,
 (0, 50430): 46.84420694159246,
 (0, 50664): 9.947688189300205,
 (0, 50873): 22.819891272177607,
 (0, 51055): 56.46278814081552,
 (0, 51498): 18.245654562628264,
 (0, 51687): 4.365457509049696,
 (0, 51973): 5.251557239042412,
 (0, 51976): 4.055323702802042,
 (0, 52152): 37.5829803647692,
 (0, 52344): 6.383233360138082,
 (0, 52562): 13.493309527514837,
 (0, 52716): 28.74046158375461,
 (0, 52880): 24.011391510572796,
 (0, 52891): 7.114581672402099,
 (0, 52970): 4.743066135589474,
 (0, 53050): 7.519856575219566,
 (0, 53103): 31.34230443202891,
 (0, 53359): 2.8733979594530483,
 (0, 53627): 7.818535599430455,
 (0, 54003): 1.8391980338212897,
 (0, 54453): 5.429772161887922,
 (0, 54831): 12.35011194776475,
 (0, 55077): 6.383233360138082,
 (0, 55217): 13.804811593234845,
 (0, 55507): 4.582449386846484,
 (0, 55745): 16.74533455764102,
 (0, 55870): 12.065643238916433,
 (0, 55918): 19.462592791111394,
 (0, 55936): 21.322089042055175,
 (0, 56152): 5.429772161887922,
 (0, 56703): 7.519856575219566,
 (0, 57663): 6.628770611788349,
 (0, 57699): 28.21815479318934,
 (0, 57742): 4.963336753432104,
 (0, 58028): 5.429772161887922,
 (0, 58889): 15.713093764841979,
 (0, 59057): 8.769797089997077,
 (0, 59231): 5.605455582360303,
 (0, 59830): 8.088570117587354,
 (0, 60128): 5.349214392275984,
 (0, 60568): 18.74822774430314,
 (0, 60687): 16.066400813895832,
 (0, 60900): 7.114581672402099,
 (0, 61042): 4.743066135589474,
 (0, 61303): 8.900025470115454,
 (0, 61581): 1.9875228976788637,
 (0, 61708): 44.25023658808155,
 (0, 61736): 14.340928268400807,
 (0, 62081): 2.391445371116669,
 (0, 62284): 11.310993496558497,
 (0, 62464): 34.20907557026988,
 (0, 62598): 10.340947100551766,
 (0, 62630): 7.790076930625769,
 (0, 62728): 4.055323702802042,
 (0, 63026): 8.375039431346924,
 (0, 63126): 29.16228061663675,
 (0, 63251): 7.5205953509163646,
 (0, 63349): 13.052230248472423,
 (0, 63471): 4.978847454131363,
 (0, 63634): 4.739775576426991,
 (0, 63684): 13.779562921052658,
 (0, 63800): 4.7892030262250485,
 (0, 64209): 5.246939836270577,
 (0, 64252): 7.369088875876796,
 (0, 64255): 6.803362247557975,
 (0, 64272): 14.460369648119368,
 (0, 64300): 50.011936719202474,
 (0, 64571): 10.527220844338967,
 (0, 64748): 14.758272791485005,
 (0, 64808): 3.1033876135263387,
 (0, 65033): 11.393161136756287,
 (0, 65149): 15.489621103749023,
 (0, 65427): 6.33141949892024,
 (0, 65455): 13.019915421346987,
 (0, 65656): 10.094069523479472,
 (0, 65706): 13.804811593234845,
 (0, 65732): 8.088570117587354,
 (0, 65856): 13.523869638735206,
 (0, 65890): 6.153428358186903,
 (0, 66300): 21.91724081163786,
 (0, 66461): 5.210022680783289,
 (0, 66652): 6.383233360138082,
 (0, 66779): 12.7417558236736,
 (0, 66903): 13.12531215757987,
 (0, 66921): 30.236291567839007,
 (0, 66936): 2.8733979594530483,
 (0, 67524): 20.82087854683175,
 (0, 67638): 5.657781197876548,
 (0, 68151): 11.593256040921371,
 (0, 68235): 12.02385832214549,
 (0, 68575): 23.756029823808674,
 (0, 68830): 31.737006931142723,
 (0, 68892): 11.856525052487697,
 (0, 69025): 5.210022680783289,
 (0, 69047): 9.506688722243052,
 (0, 69145): 19.06758775718755,
 (0, 69162): 7.341994012169583,
 (0, 69287): 14.6666952820411,
 (0, 69410): 4.743583227021795,
 (0, 69702): 13.752322236014876,
 (0, 69842): 2.9935832270217957,
 (0, 70411): 18.11679274071381,
 (0, 70419): 2.391445371116669,
 (0, 70676): 11.013219065048894,
 (0, 70739): 17.810136436048808,
 (0, 70924): 31.830646229638287,
 (0, 71440): 12.04101455801463,
 (0, 71778): 4.548486765296348,
 (0, 71840): 5.657781197876548,
 (0, 71903): 28.213528858243798,
 (0, 72410): 6.383233360138082,
 (0, 72691): 8.375039431346924,
 (0, 72706): 5.657781197876548,
 (0, 72869): 21.508416387495387,
 (0, 72958): 11.362080814269444,
 (0, 73527): 10.766484802463593,
 (0, 73615): 15.992020617821767,
 (0, 73881): 27.69311041014158,
 (0, 74021): 9.481522193988006,
 (0, 74160): 9.114225589195934,
 (0, 74461): 2.023054008169132,
 (0, 74520): 8.375039431346924,
 (0, 74648): 10.867803878659837,
 (0, 74671): 8.004882296741023,
 (0, 74694): 16.594132825256082,
 (0, 74917): 14.401028198853396,
 (0, 74938): 18.87377625507066,
 (0, 75122): 23.744154142011478,
 (0, 75169): 4.978847454131363,
 (0, 75194): 12.04101455801463,
 (0, 75352): 10.691933558883504,
 (0, 75806): 6.050370342243182,
 (0, 75843): 5.7147064826460365,
 (0, 75887): 6.383233360138082,
 (0, 75960): 17.637654552335555,
 (0, 75962): 10.364354566481145,
 (0, 76279): 19.443353790110823,
 (0, 76422): 5.887761274999198,
 (0, 76488): 32.22110274820774,
 (0, 76537): 13.493309527514837,
 (0, 76604): 17.774823440809676,
 (0, 76991): 11.450483181842058,
 (0, 77119): 22.57425202272429,
 (0, 77178): 5.262426482967963,
 (0, 77268): 11.593256040921371,
 (0, 77293): 8.763633290782717,
 (0, 77577): 2.6255056488550004,
 (0, 77639): 8.375039431346924,
 (0, 77773): 3.1349578805276646,
 (0, 77880): 21.589063447407007,
 (0, 78203): 5.210022680783289,
 (0, 78323): 14.758272791485005,
 (0, 78390): 5.251557239042412,
 (0, 78398): 11.852485483995352,
 (0, 78420): 11.097783955782486,
 (0, 78774): 4.049900026804748,
 (0, 79374): 5.355067064114578,
 (0, 79665): 4.743583227021795,
 (0, 80024): 5.605455582360303,
 (0, 80380): 4.963336753432104,
 (0, 80660): 2.391445371116669,
 (0, 80758): 7.114581672402099,
 (0, 80853): 24.39853461615087,
 (0, 80898): 14.262800706346122,
 (0, 80987): 7.556242818183537,
 (0, 81034): 2.184862950559213,
 (0, 81102): 48.965693274907295,
 (0, 81138): 19.02759965453267,
 (0, 81253): 4.197407749766994,
 (0, 81265): 5.657781197876548,
 (0, 81306): 15.374927729042788,
 (0, 81481): 5.165539052776976,
 (0, 81688): 16.258880154088818,
 (0, 81893): 7.556242818183537,
 (0, 82045): 3.837831227249148,
 (0, 82094): 11.08755335976447,
 (0, 82564): 10.714075766442354,
 (0, 82584): 18.94383176713933,
 (0, 82872): 24.28259890958771,
 (0, 83025): 6.383233360138082,
 (0, 83116): 47.95585464718852,
 (0, 83150): 8.088570117587354,
 (0, 83309): 11.404985597229315,
 (0, 83341): 15.525424657289365,
 (0, 83581): 2.391445371116669,
 (0, 83698): 5.498903608308049,
 (0, 83743): 17.206553610791605,
 (0, 83809): 8.088570117587354,
 (0, 83813): 5.465288357811696,
 (0, 83816): 4.963336753432104,
 (0, 83898): 9.937516450961063,
 (0, 84086): 6.628770611788349,
 (0, 84095): 14.540069937454415,
 (0, 84281): 25.553567267939425,
 (0, 84486): 19.94191718159885,
 (0, 84522): 7.756387633325582,
 (0, 84796): 5.039797161407152,
 (0, 84838): 15.112485636367074,
 (0, 85085): 34.667436253528344,
 (0, 85301): 14.796361454264051,
 (0, 85309): 4.548486765296348,
 (0, 85355): 6.383233360138082,
 (0, 85437): 10.173355388909718,
 (0, 85520): 10.115361061894907,
 (0, 85542): 11.08755335976447,
 (0, 85736): 4.978847454131363,
 (0, 85774): 8.602931011598965,
 (0, 85795): 10.408619616019285,
 (0, 85904): 5.657781197876548,
 (0, 86748): 19.94299541022938,
 (0, 86869): 5.887761274999198,
 (0, 87022): 13.518342279475277,
 (0, 87092): 13.476316797307003,
 (0, 87560): 4.402355101601121,
 (0, 87599): 5.657781197876548,
 (0, 87678): 5.165539052776976,
 (0, 87683): 3.308914782816706,
 (0, 87815): 3.8187966691783846,
 (0, 87969): 2.8733979594530483,
 (0, 87994): 12.338524209346438,
 (0, 88165): 23.455606798291363,
 (0, 88222): 10.595311214664898,
 (0, 88260): 5.657781197876548,
 (0, 88802): 5.465288357811696,
 (0, 89052): 12.106900733033067,
 (0, 89113): 5.928262526243849,
 (0, 89170): 3.756625231909141,
 (0, 89248): 13.118622658368718,
 (0, 89454): 8.22267763209669,
 (0, 89509): 1.8515296172258795,
 (0, 89621): 16.527556117670407,
 (0, 89789): 6.383233360138082,
 (0, 89853): 10.413539526063794,
 (0, 90296): 12.7417558236736,
 (0, 90545): 8.553768175098849,
 (0, 90629): 2.6255056488550004,
 (0, 91043): 16.95898593814844,
 (0, 91151): 15.080125526102655,
 (0, 91252): 149.73508845434776,
 (0, 91501): 6.383233360138082,
 (0, 91714): 10.714075766442354,
 (0, 91859): 11.85435724882909,
 (0, 92053): 6.383233360138082,
 (0, 92177): 9.516657070702614,
 (0, 92213): 6.383233360138082,
 (0, 92587): 7.556242818183537,
 (0, 92629): 6.253470561290988,
 (0, 92643): 24.527356793213563,
 (0, 92714): 9.953605907805084,
 (0, 92799): 6.383233360138082,
 (0, 92881): 26.09865111868661,
 (0, 92967): 4.402355101601121,
 (0, 93179): 18.97433290808718,
 (0, 93227): 11.593256040921371,
 (0, 93710): 55.054977923032304,
 (0, 93948): 5.287667149714298,
 (0, 94184): 2.4305181486146146,
 (0, 94189): 27.244166348004082,
 (0, 94325): 30.606539798052935,
 (0, 94424): 4.978847454131363,
 (0, 94463): 1.9588389821883334,
 (0, 94577): 26.861518531681977,
 (0, 94716): 4.888641741225548,
 (0, 94750): 6.790076930625769,
 (0, 94970): 5.429772161887922,
 (0, 95096): 5.145249639121136,
 (0, 95232): 4.743583227021795,
 (0, 95267): 5.887761274999198,
 (0, 95462): 17.300616365053994,
 (0, 95678): 4.7631054952212555,
 (0, 95981): 4.739775576426991,
 (0, 96037): 15.480870049551363,
 (0, 96435): 102.24251201808107,
 (0, 96687): 11.775522549998396,
 (0, 97295): 11.35803468813177,
 (0, 97433): 11.513020729992839,
 (0, 97599): 7.556242818183537,
 (0, 97615): 8.088570117587354,
 (0, 97636): 7.197626034026515,
 (0, 97930): 6.383233360138082,
 (0, 98212): 40.69602624350691,
 (0, 98269): 12.771413814261978,
 (0, 98272): 7.114581672402099,
 (0, 98483): 8.544873729303571,
 (0, 98552): 17.786035260455037,
 (0, 98591): 6.660296311615992,
 (0, 98614): 87.10158619298902,
 (0, 98632): 4.197407749766994,
 (0, 98677): 50.77434881418646,
 (0, 99055): 11.775522549998396,
 (0, 99762): 13.140095908518115,
 (0, 100305): 6.383233360138082,
 (0, 100452): 16.684138948490453,
 (0, 100883): 6.803362247557975,
 (0, 101061): 2.391445371116669,
 (0, 101232): 4.874868330088946,
 (0, 101253): 16.29757604054776,
 (0, 101259): 5.76916198695716,
 (0, 101261): 10.973699804698864,
 (0, 101733): 6.1575508195407505,
 (0, 101813): 5.210022680783289,
 (0, 101827): 7.757460673333362,
 (0, 101907): 35.841963890894874,
 (0, 102502): 12.544353834290021,
 (0, 102542): 9.616880830807574,
 (0, 102663): 37.279019017326675,
 (0, 102765): 20.622273464958027,
 (0, 102923): 5.657781197876548,
 (0, 103233): 2.9935832270217957,
 (0, 103598): 4.963336753432104,
 (0, 103616): 15.187943563340324,
 (0, 103695): 4.743066135589474,
 (0, 103776): 12.303863316873933,
 (0, 104138): 37.768163265941915,
 (0, 104193): 10.557893612243555,
 (0, 104310): 11.74816992608741,
 (0, 104528): 7.790076930625769,
 (0, 104535): 23.546076454208926,
 (0, 104579): 2.4305181486146146,
 (0, 104972): 8.375039431346924,
 (0, 105039): 10.631344502020994,
 (0, 105910): 4.557112794597967,
 (0, 106046): 4.743583227021795,
 (0, 106110): 5.657781197876548,
 (0, 106206): 17.505510512636267,
 (0, 106207): 2.6255056488550004,
 (0, 106421): 5.887761274999198,
 (0, 106496): 7.790076930625769,

In [68]:
g=df_final.groupby(['user_idx'])["tf-idf"]

In [69]:
df_final.loc[:,"Rating"]=g.transform(lambda x:pd.cut(x.rank(pct=True),bins=5,labels=[1,2,3,4,5]))

In [70]:
df_final[["user_idx","song_idx","Rating"]].to_csv("user_song_interacting.csv")

In [71]:
df_final.head()

   user_idx  song_idx     tf-idf Rating
0         0        83  17.286297      5
1         0       117  30.094128      5
2         0       165  17.772142      5
3         0       474   2.023054      1
4         0       720   9.506027      3

In [54]:
with open('song2idx.txt', 'w') as convert_file:
     convert_file.write(json.dumps(song2idx))

In [55]:
with open('user2idx.txt', 'w') as convert_file:
     convert_file.write(json.dumps(user2idx))